#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_hat_factory_ai = env_modules.Clone()
env_hat_factory_ai.Prepend(CPPPATH=[Dir(".")])

env_hat_factory_ai.add_source_files(env.modules_sources, "*.cpp")
