#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_hat_factory_hex_grid = env_modules.Clone()

# Module sources
env_hat_factory_hex_grid.add_source_files(env.modules_sources, "*.cpp")
